#############################################################################
# Makefile for building: CS1CProject2BulkClub.app/Contents/MacOS/CS1CProject2BulkClub
# Generated by qmake (3.1) (Qt 5.12.6)
# Project:  CS1CProject2BulkClub.pro
# Template: app
# Command: /Users/billy/Desktop/Qt/5.12.6/clang_64/bin/qmake -o Makefile CS1CProject2BulkClub.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -fPIC $(DEFINES)
INCPATH       = -I. -I../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers -I../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/OpenGL.framework/Headers -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/AGL.framework/Headers -I. -I../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib
QMAKE         = /Users/billy/Desktop/Qt/5.12.6/clang_64/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/billy/Desktop/Qt/5.12.6/clang_64/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/billy/Desktop/Qt/5.12.6/clang_64/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = CS1CProject2BulkClub1.0.0
DISTDIR = /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/.tmp/CS1CProject2BulkClub1.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ -headerpad_max_install_names $(EXPORT_ARCH_ARGS) -Wl,-syslibroot,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wl,-rpath,@executable_path/../Frameworks -Wl,-rpath,/Users/billy/Desktop/Qt/5.12.6/clang_64/lib
LIBS          = $(SUBLIBS) -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib -framework QtWidgets -framework QtGui -framework QtSql -framework QtCore -framework DiskArbitration -framework IOKit -framework OpenGL -framework AGL   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = adminpage.cpp \
		dbmanager.cpp \
		main.cpp \
		mainwindow.cpp \
		storemanagerpage.cpp \
		yesno.cpp moc_adminpage.cpp \
		moc_mainwindow.cpp \
		moc_storemanagerpage.cpp \
		moc_yesno.cpp
OBJECTS       = adminpage.o \
		dbmanager.o \
		main.o \
		mainwindow.o \
		storemanagerpage.o \
		yesno.o \
		moc_adminpage.o \
		moc_mainwindow.o \
		moc_storemanagerpage.o \
		moc_yesno.o
DIST          = ../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		CS1CProject2BulkClub.pro adminpage.h \
		dbmanager.h \
		mainwindow.h \
		storemanagerpage.h \
		yesno.h adminpage.cpp \
		dbmanager.cpp \
		main.cpp \
		mainwindow.cpp \
		storemanagerpage.cpp \
		yesno.cpp
QMAKE_TARGET  = CS1CProject2BulkClub
DESTDIR       = 
TARGET        = CS1CProject2BulkClub.app/Contents/MacOS/CS1CProject2BulkClub

####### Custom Variables
EXPORT_QMAKE_MAC_SDK = macosx
EXPORT_QMAKE_MAC_SDK_VERSION = 10.15
EXPORT_QMAKE_XCODE_DEVELOPER_PATH = /Applications/Xcode.app/Contents/Developer
EXPORT_VALID_ARCHS = x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT__PRO_FILE_ = /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/CS1CProject2BulkClub.pro


include /Users/billy/Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.mk
first: all
####### Build rules

CS1CProject2BulkClub.app/Contents/MacOS/CS1CProject2BulkClub: ui_adminpage.h ui_mainwindow.h ui_storemanagerpage.h ui_yesno.h $(OBJECTS)  
	@test -d CS1CProject2BulkClub.app/Contents/MacOS/ || mkdir -p CS1CProject2BulkClub.app/Contents/MacOS/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: CS1CProject2BulkClub.pro ../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf ../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/qdevice.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/unix.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/macx.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/qconfig.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf \
		.qmake.stash \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resources.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/moc.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/uic.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf \
		../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/lex.prf \
		CS1CProject2BulkClub.pro \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/QtSql.prl \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl
	$(QMAKE) -o Makefile CS1CProject2BulkClub.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_pre.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/qdevice.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/device_config.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/unix.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/mac.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/macx.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/sanitize.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/gcc-base-mac.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/common/clang-mac.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/qconfig.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3danimation_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dcore_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dextras_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dinput_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dlogic_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquick_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_3drender_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bluetooth_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_bootstrap_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_charts_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_concurrent_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_core_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_datavisualization_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_dbus_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designer_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_designercomponents_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_edid_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fb_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gamepad_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_graphics_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_gui_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_help_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_location_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_macextras_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimedia_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_network_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_networkauth_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_nfc_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_opengl_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_openglextensions_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioning_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_positioningquick_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_printsupport_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_purchasing_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qml_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldebug_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qmltest_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quick_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickparticles_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickshapes_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_repparser_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_script_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scripttools_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_scxml_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sensors_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialbus_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_serialport_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_service_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_sql_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_svg_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_testlib_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_texttospeech_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_theme_support_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uiplugin.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_uitools_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webchannel_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webengine_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecore_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginecoreheaders_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_websockets_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_webview_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_widgets_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xml_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_functions.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt_config.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang/qmake.conf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/spec_post.prf:
.qmake.stash:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exclusive_builds.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/sdk.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/toolchain.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/toolchain.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_pre.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_pre.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resolve_config.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/default_post.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/default_post.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/objective_c.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qml_debug.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/mac.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/warn_on.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qt.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/resources.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/moc.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/opengl.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/uic.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/unix/thread.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/qmake_use.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/file_copies.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/rez.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/mac/asset_catalogs.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/testcase_targets.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/exceptions.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/yacc.prf:
../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/lex.prf:
CS1CProject2BulkClub.pro:
../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/QtWidgets.prl:
../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/QtGui.prl:
../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/QtSql.prl:
../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/QtCore.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile CS1CProject2BulkClub.pro -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

qmake_all: FORCE

CS1CProject2BulkClub.app/Contents/PkgInfo: 
	@test -d CS1CProject2BulkClub.app/Contents || mkdir -p CS1CProject2BulkClub.app/Contents
	@$(DEL_FILE) CS1CProject2BulkClub.app/Contents/PkgInfo
	@echo "APPL????" > CS1CProject2BulkClub.app/Contents/PkgInfo
CS1CProject2BulkClub.app/Contents/Resources/empty.lproj: 
	@test -d CS1CProject2BulkClub.app/Contents/Resources || mkdir -p CS1CProject2BulkClub.app/Contents/Resources
	@touch CS1CProject2BulkClub.app/Contents/Resources/empty.lproj
	
CS1CProject2BulkClub.app/Contents/Info.plist: 
	@test -d CS1CProject2BulkClub.app/Contents || mkdir -p CS1CProject2BulkClub.app/Contents
	@$(DEL_FILE) CS1CProject2BulkClub.app/Contents/Info.plist
	@sed -e "s,@SHORT_VERSION@,1.0,g" -e "s,\$${QMAKE_SHORT_VERSION},1.0,g" -e "s,@FULL_VERSION@,1.0.0,g" -e "s,\$${QMAKE_FULL_VERSION},1.0.0,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" -e "s,@BUNDLEIDENTIFIER@,com.BillyMagdangal.CS1CProject2BulkClub,g" -e "s,\$${PRODUCT_BUNDLE_IDENTIFIER},com.BillyMagdangal.CS1CProject2BulkClub,g" -e "s,\$${MACOSX_DEPLOYMENT_TARGET},10.12,g" -e "s,\$${IPHONEOS_DEPLOYMENT_TARGET},,g" -e "s,\$${TVOS_DEPLOYMENT_TARGET},,g" -e "s,\$${WATCHOS_DEPLOYMENT_TARGET},,g" -e "s,@ICON@,,g" -e "s,\$${ASSETCATALOG_COMPILER_APPICON_NAME},,g" -e "s,@EXECUTABLE@,CS1CProject2BulkClub,g" -e "s,@LIBRARY@,CS1CProject2BulkClub,g" -e "s,\$${EXECUTABLE_NAME},CS1CProject2BulkClub,g" -e "s,@TYPEINFO@,????,g" -e "s,\$${QMAKE_PKGINFO_TYPEINFO},????,g" ../../Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang/Info.plist.app >CS1CProject2BulkClub.app/Contents/Info.plist

all: Makefile \
		CS1CProject2BulkClub.app/Contents/PkgInfo \
		CS1CProject2BulkClub.app/Contents/Resources/empty.lproj \
		CS1CProject2BulkClub.app/Contents/Info.plist CS1CProject2BulkClub.app/Contents/MacOS/CS1CProject2BulkClub

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents ../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adminpage.h dbmanager.h mainwindow.h storemanagerpage.h yesno.h $(DISTDIR)/
	$(COPY_FILE) --parents adminpage.cpp dbmanager.cpp main.cpp mainwindow.cpp storemanagerpage.cpp yesno.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adminpage.ui mainwindow.ui storemanagerpage.ui yesno.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) -r CS1CProject2BulkClub.app
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-clang CONFIG+=debug CONFIG+=x86_64 CONFIG+=qml_debug

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: ../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp
	/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -pipe -stdlib=libc++ -g -std=gnu++11 $(EXPORT_ARCH_ARGS) -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk -mmacosx-version-min=10.12 -Wall -W -dM -E -o moc_predefs.h ../../Desktop/Qt/5.12.6/clang_64/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_adminpage.cpp moc_mainwindow.cpp moc_storemanagerpage.cpp moc_yesno.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_adminpage.cpp moc_mainwindow.cpp moc_storemanagerpage.cpp moc_yesno.cpp
moc_adminpage.cpp: adminpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_adminpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		moc_predefs.h \
		../../Desktop/Qt/5.12.6/clang_64/bin/moc
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/moc_predefs.h -I/Users/billy/Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++ -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/backward -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include-fixed -IC:/Qt/Tools/mingw730_32/i686-w64-mingw32/include -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib adminpage.h -o moc_adminpage.cpp

moc_mainwindow.cpp: mainwindow.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		storemanagerpage.h \
		ui_storemanagerpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminpage.h \
		ui_adminpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		moc_predefs.h \
		../../Desktop/Qt/5.12.6/clang_64/bin/moc
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/moc_predefs.h -I/Users/billy/Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++ -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/backward -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include-fixed -IC:/Qt/Tools/mingw730_32/i686-w64-mingw32/include -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib mainwindow.h -o moc_mainwindow.cpp

moc_storemanagerpage.cpp: storemanagerpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_storemanagerpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		moc_predefs.h \
		../../Desktop/Qt/5.12.6/clang_64/bin/moc
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/moc_predefs.h -I/Users/billy/Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++ -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/backward -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include-fixed -IC:/Qt/Tools/mingw730_32/i686-w64-mingw32/include -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib storemanagerpage.h -o moc_storemanagerpage.cpp

moc_yesno.cpp: yesno.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		moc_predefs.h \
		../../Desktop/Qt/5.12.6/clang_64/bin/moc
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/moc $(DEFINES) --include /Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch/moc_predefs.h -I/Users/billy/Desktop/Qt/5.12.6/clang_64/mkspecs/macx-clang -I/Users/billy/Downloads/CS1C-Project-2-Bulk-Club-2-2.0-matt-s-branch -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers -I/Users/billy/Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++ -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/i686-w64-mingw32 -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include/c++/backward -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include -IC:/Qt/Tools/mingw730_32/lib/gcc/i686-w64-mingw32/7.3.0/include-fixed -IC:/Qt/Tools/mingw730_32/i686-w64-mingw32/include -F/Users/billy/Desktop/Qt/5.12.6/clang_64/lib yesno.h -o moc_yesno.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_adminpage.h ui_mainwindow.h ui_storemanagerpage.h ui_yesno.h
compiler_uic_clean:
	-$(DEL_FILE) ui_adminpage.h ui_mainwindow.h ui_storemanagerpage.h ui_yesno.h
ui_adminpage.h: adminpage.ui \
		../../Desktop/Qt/5.12.6/clang_64/bin/uic
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/uic adminpage.ui -o ui_adminpage.h

ui_mainwindow.h: mainwindow.ui \
		../../Desktop/Qt/5.12.6/clang_64/bin/uic
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/uic mainwindow.ui -o ui_mainwindow.h

ui_storemanagerpage.h: storemanagerpage.ui \
		../../Desktop/Qt/5.12.6/clang_64/bin/uic
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/uic storemanagerpage.ui -o ui_storemanagerpage.h

ui_yesno.h: yesno.ui \
		../../Desktop/Qt/5.12.6/clang_64/bin/uic
	/Users/billy/Desktop/Qt/5.12.6/clang_64/bin/uic yesno.ui -o ui_yesno.h

compiler_rez_source_make_all:
compiler_rez_source_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

adminpage.o: adminpage.cpp adminpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_adminpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		yesno.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QDebug \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qdebug.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adminpage.o adminpage.cpp

dbmanager.o: dbmanager.cpp dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dbmanager.o dbmanager.cpp

main.o: main.cpp mainwindow.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		storemanagerpage.h \
		ui_storemanagerpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminpage.h \
		ui_adminpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QApplication \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qapplication.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		storemanagerpage.h \
		ui_storemanagerpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h \
		adminpage.h \
		ui_adminpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QSqlQuery \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QInputDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qinputdialog.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/QIntValidator \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtGui.framework/Headers/qvalidator.h \
		ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

storemanagerpage.o: storemanagerpage.cpp storemanagerpage.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMainWindow \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmainwindow.h \
		ui_storemanagerpage.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QMessageBox \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qmessagebox.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o storemanagerpage.o storemanagerpage.cpp

yesno.o: yesno.cpp yesno.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/QDialog \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtWidgets.framework/Headers/qdialog.h \
		dbmanager.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/QObject \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtCore.framework/Headers/qobject.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/QtSql \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlglobal.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldatabase.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriver.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqldriverplugin.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlerror.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlfield.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlindex.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquery.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlquerymodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrecord.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaldelegate.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlrelationaltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqlresult.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qsqltablemodel.h \
		../../Desktop/Qt/5.12.6/clang_64/lib/QtSql.framework/Headers/qtsqlversion.h \
		ui_yesno.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o yesno.o yesno.cpp

moc_adminpage.o: moc_adminpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adminpage.o moc_adminpage.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_storemanagerpage.o: moc_storemanagerpage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_storemanagerpage.o moc_storemanagerpage.cpp

moc_yesno.o: moc_yesno.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_yesno.o moc_yesno.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin || mkdir -p $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin
	$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin/CS1CProject2BulkClub.app
	
	-$(QINSTALL) CS1CProject2BulkClub.app $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin/CS1CProject2BulkClub.app

uninstall_target: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin/CS1CProject2BulkClub.app
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/CS1CProject2BulkClub/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

